language: cpp
dist: trusty
os: linux
addons:
  apt:
    packages:
      - cmake
      - g++-7
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

cache:
  - bundler

script:
  - git clone https://github.com/google/googletest.git
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-7 C=/usr/bin/gcc-7 cmake ..
  - make all
  - ./test/GCD_test
  - valgrind ./src/GCD_run

after_success:
        - echo "success"

after_failure:
        - echo "failure"        